# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: mysql2
  encoding: utf8
  database: pomyslyonline2
  username: root
  password: root


#test:
  #<<: *default
  #database: db/test.sqlite3

#production:
  #<<: *default
  #database: db/production.sqlite3
